version: '2.0'

dir_rule:
  base_dir: /root/18comic_down/books
  rule: Bd_Aid_Pindex

client:
  impl: api
  domain:
    html:
      - 18comic.vip
      - 18comic.org
    api:
      - www.jmapiproxyxxx.vip
#  postman:
#    meta_data:
#      proxies: 127.0.0.1:7890


download:
  cache: true # 如果要下载的文件在磁盘上已存在，不用再下一遍了吧？
  image:
    decode: true # JM的原图是混淆过的，要不要还原？
    suffix: .jpg # 把图片都转为.jpg格式
  threading:
    # batch_count: 章节的批量下载图片线程数
    # 数值大，下得快，配置要求高，对禁漫压力大
    # 数值小，下得慢，配置要求低，对禁漫压力小
    # PS: 禁漫网页一般是一次请求50张图
    batch_count: 10
plugins:
  after_album:
    - plugin: img2pdf
      kwargs:
        pdf_dir: /root/18comic_down/ # pdf存放文件夹
        filename_rule: Aid # Aname # pdf命名规则，A代表album, name代表使用album.name也就是本子名称